name: mac
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: fastai/workflows/ssh@master
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        key_file: id_ecdsa
    - uses: actions/checkout@v2
    - run: source script-mac.sh
    - env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }} 
    - run: ngrok authtoken "$NGROK_AUTH_TOKEN"
    - run: ngrok tcp 5900 &
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2
